sudo: required
services:
  - docker

before-install:
  - docker build -t arahanthjain/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t arahanthjain/multi-client ./client
  - docker build -t arahanthjain/multi-nginx ./nginx
  - docker build -t arahanthjain/multi-server ./server
  - docker build -t arahanthjain/multi-worker ./worker