sudo: required
services:
  - docker

before-install:
  - docker build -t arahanthjain/react-test -f ./client/Dockerfile.dev

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t arahanthjain/multi-client ./client
  - docker build -t arahanthjain/multi-nginx ./nginx
  - docker build -t arahanthjain/multi-server ./server
  - docker build -t arahanthjain/multi-worker ./worker

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID"

  - docker push arahanthjain/multi-client
  - docker push arahanthjain/multi-nginx
  - docker push arahanthjain/multi-server
  - docker push arahanthjain/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker.env
  bucket_name:
  bucket_path:
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY